import { Inter } from "next/font/google";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import "./globals.css";
import "@/public/css/style.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const session = await getServerSession(authOptions);

    return (
        <html lang="en">
            <body className={inter.className}>
                <div id="app">
                    <div className="off" id="wrapper">
                        {children}
                    </div>
                </div>
            </body>
        </html>
    );
}
